#!/usr/bin/env bash
# Render Static Site build command:  bash build.sh
# Reads VITE_API_URL from the environment and writes it into env.js,
# so the backend address is never hardcoded in index.html.
set -e

API="${VITE_API_URL:-${API_URL:-}}"
API="${API%/}"          # strip any trailing slash

if [ -z "$API" ]; then
  echo "WARNING: VITE_API_URL is not set. The portal will show a setup banner."
else
  echo "Building with API_URL=$API"
fi

cat > env.js <<JS
/* Generated by build.sh — do not edit. */
window.__APP_ENV__ = { API_URL: "${API}" };
JS

echo "env.js written."
